### PR TITLE
feat: add goto command

### PR DESCRIPTION
**Pull request by SparkyCloudy**

### CODE REVIEW

**Comment by SparkyCloudy** [comment]
@oylsister

**Comment by SparkyCloudy** [comment]
> L 11/25/2023 - 14:00:14: "Sparky<0><[U:1:384725298]><CT>" say "!goto Goggles"
> Couldn't resolve offset 280 in CCSPlayerController at path (-1 = '')
> Couldn't resolve offset 248 in CCSPlayerController at path (-1 = '')
> Couldn't resolve offset 240 in CCSPlayerController at path (-1 = '')
> Couldn't resolve offset 256 in CCSPlayerController at path (-1 = '')
> Couldn't resolve offset 242 in CCSPlayerController at path (-1 = '')
> Couldn't resolve offset 264 in CCSPlayerController at path (-1 = '')
> Couldn't resolve offset 244 in CCSPlayerController at path (-1 = '')
> SV:  1/CCSPlayerController:  requested resolve all 9 changes, actually resolved only 2 changes
> SV:    0                                      280 not resolved
> SV:    2                                      248 not resolved
> SV:    3                                      240 not resolved
> SV:    4                                      256 not resolved
> SV:    5                                      242 not resolved
> SV:    6                                      264 not resolved
> SV:    7                                      244 not resolved

**Comment by oylsister** [comment]
so it work or not?

**Comment by SparkyCloudy** [comment]
already made the fix

**Pull request merged**
